### ISSUE TITLE
ViT-L

### ISSUE THREAD

**Issue by RuoyuChen10** [Cyang-Zhao/Grad-Eclip#1]
你好，我想在ViT-L测试，是不是直接把你导入CLIP的代码的ViT-B改成ViT-L，这样兼容么？

**Comment by Cyang-Zhao** [comment]
直接替换load的模型就可以了

**Comment by RuoyuChen10** [comment]
> 直接替换load的模型就可以了

嗯嗯我已经复现出来结果了，在Xplique库上评价对比了你们的方法，VIT-L的Insertion还有Deletion数值和你们Paper里ViT-B的差不多，这将是一个很好的对比baseline。

**Comment by Cyang-Zhao** [comment]
嗯嗯，多谢关注！
