### ISSUE TITLE
text

### ISSUE THREAD

**Issue by mess-in-a-dress** [Cyang-Zhao/Grad-Eclip#2]
您好，代码里文本解释的可视化部分运行后显示不出单词重要性

**Comment by Cyang-Zhao** [comment]
请问具体是什么报错呢

**Comment by mess-in-a-dress** [comment]
vis_data_records = [visualization.VisualizationDataRecord(grad_emap,0,0,0,0,0,text_tokens_decoded,1)]
visualization.visualize_text(vis_data_records)
这个可视化函数得出的结果显示不出想要的显示哪个单词的重要性，可以给出具体一点的办法吗，小白刚刚学可解释的可视化不太搞得清楚

**Comment by Cyang-Zhao** [comment]
![image](https://github.com/user-attachments/assets/62b5e2b9-e370-4c1e-9fd3-855d25c039ce)
这是正常运行的结果，可视化了每个单词的重要性。可以描述你运行结果的具体错误吗，而不是只说显示不出来？

**Comment by mess-in-a-dress** [comment]
![8b29f023-4c29-4f10-a603-477b5fa08f36](https://github.com/user-attachments/assets/b018d533-539e-4b7a-a9aa-ba5854942b56)
具体是这样的

**Comment by Cyang-Zhao** [comment]
看一下第10个cell的输出是不是正确的，如下：
![image](https://github.com/user-attachments/assets/6e2c179d-21e1-48e0-acf0-4880cfd83af0)

如果是grad-eclip结果正确，请检查 from captum.attr import visualization 的visualization函数
如果不正确，可否提供一下grad-eclip计算时每个cell的输出

**Comment by mess-in-a-dress** [comment]
运行结果如下：
tensor([0.2874, 0.1035, 0.0351, 0.1780, 0.0534, 0.0000, 0.1460, 0.1849, 0.0115],
       device='cuda:0', dtype=torch.float16, grad_fn=<DivBackward0>)
visualization函数如下：
vis_data_records = [visualization.VisualizationDataRecord(grad_emap,0,0,0,0,0,text_tokens_decoded,1)]
这个函数里的参数pred_prob, pred_class,true_class,attr_class,attr_score该怎么获得呢，还是就是里面的0就可以

**Comment by Cyang-Zhao** [comment]
grad-eclip的计算结果是正常的，visualization我这里使用的是 from captum.attr import visualization 这个包的默认用法，只是用来显示word importance， 不涉及到pred_prob, pred_class,true_class,attr_class,attr_score这些。建议你去google captum.attr 里visualization的相关问题，我这边是可以正常显示的。
